#!/bin/sh
set -e

lb config noauto \
  --architectures amd64 \
  --distribution trixie \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images iso-hybrid \
  --bootloaders grub-efi \
  --debian-installer none \
  --bootappend-live "boot=live components locales=en_US.UTF-8 keyboard-layouts=us hostname=acabos-installer username=root" \
  --debootstrap-options "--include=ca-certificates" \
  --linux-flavours amd64 \
  --system live \
  --initsystem systemd \
  --initramfs dracut-live \
  --chroot-filesystem squashfs \
  --firmware-binary true \
  --firmware-chroot true \
    --checksums md5 \
--apt-indices false
