#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

# BASE_INSTALL -- Bootstrap Debian Trixie via mmdebstrap with pinned packages.
# Strategy: boot-critical packages via --include, expanded packages via customize-hook.
# Re-entry probe: lib/probes.sh probe_base_install()
run_base_install() {
  log "=== BASE_INSTALL ==="

  local pool_name hostname target_disk
  pool_name=$(state_get_field "pool_name")
  hostname=$(state_get_field "hostname")
  target_disk=$(state_get_field "target_disk")
  local target="/mnt/install"

  [[ -d "$target/bin" ]] && {
    warn "Target already populated. Running dataset rerun..."
    prepare_dataset_rerun "$pool_name"
  }

  log "Mounting ROOT dataset..."
  run_timeout "$SHORT_TIMEOUT" zfs set mountpoint="${target}" "${pool_name}/ROOT/acabos" \
    || fail "Failed to set mountpoint for ${pool_name}/ROOT/acabos"
  run_timeout "$SHORT_TIMEOUT" zfs mount "${pool_name}/ROOT/acabos" \
    || fail "Failed to mount ${pool_name}/ROOT/acabos at ${target}"

  log "Running mmdebstrap..."
  log "  target: ${target}"
  log "  hostname: ${hostname}"

  local incl="init,linux-image-amd64,linux-headers-amd64"
  incl+=",zfsutils-linux,zfs-dkms,zfs-dracut,zfs-zed,dracut"
  incl+=",openssh-server,sudo,curl,bash-completion,dbus"
  incl+=",gum,fzf"
  incl+=",locales,console-setup,console-data,kbd,iproute2"
  incl+=",build-essential,pkg-config,libssl-dev,dkms"
  incl+=",python3,python3-pip,python3-venv,python3-dev,python3-full,python-is-python3"

  run_timeout "$BUILD_TIMEOUT" mmdebstrap \
    --mode=unshare \
    --variant=important \
    --include=systemd,locales,dbus,openssh-server,zfsutils-linux,zfs-zed,dracut \
    --setup-hook='mkdir -p "$1/etc/apt/sources.list.d" "$1/etc/apt/preferences.d"' \
    --setup-hook="cp ${INSTALLER_DIR}/config/apt-sources.list \"\$1\"/etc/apt/sources.list" \
    --setup-hook="cp ${INSTALLER_DIR}/config/apt-preferences \"\$1\"/etc/apt/preferences.d/99-acabos-cohort" \
    --customize-hook="chroot \"\$1\" bash -c 'echo ${hostname} > /etc/hostname'" \
    --customize-hook="cp ${INSTALLER_DIR}/config/apt-trust.conf \"\$1\"/etc/apt/apt.conf.d/99-acabos-trust" \
    --customize-hook="chroot \"\$1\" systemctl enable ssh dbus zfs-zed || true" \
    --customize-hook="mkdir -p \"\$1\"/opt/acab/models/manifests \"\$1\"/opt/acab/prompts/system \"\$1\"/opt/acab/prompts/envelopes \"\$1\"/opt/acab/policies/runtime \"\$1\"/opt/acab/policies/adjudication \"\$1\"/opt/acab/hooks/bin \"\$1\"/opt/acab/hooks/specs \"\$1\"/opt/acab/state/queues \"\$1\"/opt/acab/state/runs \"\$1\"/opt/acab/state/transcripts \"\$1\"/opt/acab/state/cache \"\$1\"/opt/acab/logs/llama \"\$1\"/opt/acab/logs/hooks \"\$1\"/opt/acab/logs/agent \"\$1\"/opt/acab/logs/install \"\$1\"/opt/acab/manifests \"\$1\"/opt/acab/doctor \"\$1\"/opt/acab/services/env \"\$1\"/opt/acab/bin" \
    --customize-hook="mkdir -p \"\$1\"/opt/ai-venv \"\$1\"/opt/llama-cpp" \
    --customize-hook="chroot \"\$1\" bash -c 'echo \"en_US.UTF-8 UTF-8\" > /etc/locale.gen && locale-gen'" \
    --customize-hook="chroot \"\$1\" bash -c 'echo \"LANG=en_US.UTF-8\" > /etc/default/locale'" \
    --customize-hook="chroot \"\$1\" bash -c 'ln -sf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone'" \
    --include="$incl" \
    trixie "$target" http://deb.debian.org/debian \
    || fail "mmdebstrap failed"

  log "mmdebstrap completed."

  log "Mounting EFI partition..."
  local efi_part="/dev/disk/by-id/${target_disk}-part1"
  run_timeout "$SHORT_TIMEOUT" mkdir -p "${target}/boot/efi"
  run_timeout "$SHORT_TIMEOUT" mount "$efi_part" "${target}/boot/efi" \
    || fail "Failed to mount EFI partition"
  log "EFI mounted at ${target}/boot/efi."

  log "Writing fstab..."
  local boot_efi_dev
  boot_efi_dev=$(findmnt -n -o SOURCE /mnt/install/boot/efi 2>/dev/null || echo "")
  local efi_uuid
  if [[ -n "$boot_efi_dev" ]]; then
    efi_uuid=$(blkid -s UUID -o value "$boot_efi_dev" 2>/dev/null || echo "")
  fi
  {
    echo "# ACABOS fstab - generated by installer"
    if [[ -n "$efi_uuid" ]]; then
      echo "UUID=${efi_uuid} /boot/efi vfat defaults 0 2"
    fi
    echo "/dev/zvol/${pool_name}/swap none swap sw,discard 0 0"
    echo "tmpfs /tmp tmpfs defaults 0 0"
  } > "${target}/etc/fstab"
  log "fstab written."

  log "Writing keyboard configuration..."
  cat > "${target}/etc/default/keyboard" << 'KEYBOARD'
XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""
BACKSPACE="guess"
KEYBOARD
  log "Keyboard configuration written."

  log "Configuring SSH hardening..."
  mkdir -p "${target}/etc/ssh/sshd_config.d"
  cp "${INSTALLER_DIR}/config/ssh-hardening.conf" "${target}/etc/ssh/sshd_config.d/hardening.conf"
  log "SSH hardening configured."

  log "Configuring journald..."
  mkdir -p "${target}/etc/systemd/journald.conf.d"
  cat > "${target}/etc/systemd/journald.conf.d/storage.conf" << 'JOURNALD'
[Journal]
Storage=persistent
Compress=yes
SystemMaxUse=500M
RuntimeMaxUse=100M
JOURNALD
  log "Journald configured."

  log "Writing /etc/hosts..."
  cat > "${target}/etc/hosts" << HOSTS
127.0.0.1 localhost
127.0.1.1 ${hostname}
::1       localhost ip6-localhost ip6-loopback
ff02::1   ip6-all-nodes
ff02::2   ip6-all-routers
HOSTS
  log "/etc/hosts written."

  log "Running post-mmdebstrap DKMS rebuild..."
  chroot_mount "$target"
  local target_kernel
  target_kernel=$(ls "${target}/lib/modules/" 2>/dev/null | head -1 || echo "")
  if [[ -n "$target_kernel" ]]; then
    log "Building DKMS for kernel: ${target_kernel}"
    run_timeout "$LONG_TIMEOUT" chroot "$target" dkms autoinstall -k "$target_kernel" \
      || { chroot_umount "$target"; warn "DKMS autoinstall had errors (may succeed on first boot)"; }
  else
    warn "No kernel found in target for DKMS rebuild"
  fi
  chroot_umount "$target"
  log "DKMS rebuild completed."

  log "Validating base install..."
  [[ -f "${target}/bin/bash" ]] || fail "bash not found in target"

  local k_ver h_ver
  chroot_mount "$target"
  k_ver=$(run_timeout "$SHORT_TIMEOUT" chroot "$target" dpkg-query -W -f='${Version}' linux-image-amd64 2>/dev/null || echo "")
  h_ver=$(run_timeout "$SHORT_TIMEOUT" chroot "$target" dpkg-query -W -f='${Version}' linux-headers-amd64 2>/dev/null || echo "")
  log "Kernel version: ${k_ver}"
  log "Headers version: ${h_ver}"
  [[ "$k_ver" == "$h_ver" ]] || fail "Kernel/headers version mismatch: kernel=${k_ver} headers=${h_ver}"

  local dkms_status
  dkms_status=$(run_timeout "$SHORT_TIMEOUT" chroot "$target" dkms status zfs 2>/dev/null || echo "")
  chroot_umount "$target"
  echo "$dkms_status" | grep -q "installed" || fail "ZFS DKMS not installed: ${dkms_status}"
  log "ZFS DKMS verified."

  [[ -f "${target}/etc/apt/preferences.d/99-acabos-cohort" ]] || fail "APT preferences missing"
  [[ -f "${target}/etc/apt/apt.conf.d/99-acabos-trust" ]] || fail "APT trust conf missing"
  [[ -d "${target}/opt/acab/models" ]] || fail "/opt/acab skeleton missing"
  [[ -d "${target}/opt/ai-venv" ]] || fail "/opt/ai-venv directory missing"
  [[ -d "${target}/opt/llama-cpp" ]] || fail "/opt/llama-cpp directory missing"

  log "Resetting ROOT dataset mountpoint for installed system..."
  zfs unmount "${pool_name}/ROOT/acabos" 2>/dev/null || true
  run_timeout "$SHORT_TIMEOUT" zfs set mountpoint=/ "${pool_name}/ROOT/acabos" \
    || fail "Failed to reset mountpoint on ${pool_name}/ROOT/acabos"
  log "ROOT dataset mountpoint reset to /."

  run_timeout "$SHORT_TIMEOUT" umount "${target}/boot/efi" 2>/dev/null || true

  log "BASE_INSTALL complete."
  return 0
}
