#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

if command -v sway-nvidia >/dev/null 2>&1; then
    exec sway-nvidia
else
    exec sway
fi
