#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

export __GLX_VENDOR_LIBRARY_NAME=nvidia
export _JAVA_AWT_WM_NONREPARENTING=1
export GBM_BACKEND=nvidia-drm
export __GL_GSYNC_ALLOWED=1
export __GL_VRR_ALLOWED=1
export WLR_NO_HARDWARE_CURSORS=1
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GDK_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export CUDA_CACHE_DISABLE=0
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

exec sway "$@"
