options zfs zfs_arc_max=8589934592
options zfs zfs_arc_min=1073741824
options zfs zfs_prefetch_disable=0
options zfs zfs_txg_timeout=5
options zfs zfs_vdev_async_read_max_active=10
options zfs zfs_vdev_async_write_max_active=10
options zfs zfs_vdev_scrub_max_active=2
options zfs l2arc_write_max=8388608
options zfs l2arc_write_boost=8388608
options zfs l2arc_noprefetch=0
options zfs l2arc_headroom=200
options zfs zfs_scan_scrub_after_resilver=0
