[containers]
default_capabilities = [
    "CHOWN",
    "DAC_OVERRIDE",
    "FOWNER",
    "FSETID",
    "KILL",
    "NET_BIND_SERVICE",
    "SETFCAP",
    "SETGID",
    "SETPCAP",
    "SETUID",
    "SYS_CHROOT"
]

default_ulimits = [
    "nofile=65535:65535",
    "nproc=65535:65535"
]

[engine]
runtime = "crun"
network_backend = "netavark"
log_driver = "journald"
infra_image = "docker.io/gcr.io/pause:3.9"
compose_providers = ["podman-compose"]
